import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const jsonPath = path.join(__dirname, 'vegetable_overview_all.json');
const j = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

const add = (id, o) => {
  if (j[id]) {
    console.log('skip existing', id);
    return;
  }
  j[id] = {
    sow: o.sow ?? [],
    plant: o.plant ?? [],
    harvest: o.harvest,
    standplaats: o.standplaats,
    water: o.water,
    difficulty: o.difficulty ?? 'Gemiddeld',
    lifespan: o.lifespan,
    outdoor: o.outdoor ?? 'Buiten',
    container: o.container ?? 'Bed / Pot',
    voeding: o.voeding ?? 'Gemiddeld',
    height: o.height,
    width: o.width,
    habit: o.habit,
    spacing: o.spacing,
    row: o.row ?? o.spacing,
    first: o.first,
    period: o.period,
    yield_level: o.yield_level ?? 'Gemiddelde opbrengst',
    yield_detail: o.yield_detail,
    points: o.points,
    summary: o.summary,
    know: o.know,
  };
};

add('artisjok', {
  sow: [2, 3],
  plant: [4, 5],
  harvest: [6, 7, 8, 9],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Gemiddeld',
  lifespan: 'Meerjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Hoog',
  height: '100–150 cm',
  width: '80–120 cm',
  habit: 'Grote meerjarige composiet',
  spacing: '80–100 cm',
  row: '100–120 cm',
  first: 'vanaf 2e jaar',
  period: 'juni – september',
  yield_level: 'Gemiddelde opbrengst',
  yield_detail: '4–8 bloemknoppen per plant na vestiging',
  points: [
    'Meerjarig bed',
    'Ruimte geven',
    'Oogst vóór open bloei',
    'Winterbescherming in kou',
  ],
  summary:
    'Artisjok is een imposante meerjarige groente. Plant op een zonnige, rijke plek en oogst de knoppen vóór ze openspringen.',
  know: 'In strenge winters mulchen of afdekken; jonge planten zijn gevoeliger dan oudere.',
});

add('kardoen', {
  sow: [3, 4],
  plant: [5, 6],
  harvest: [9, 10, 11],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Hoog',
  height: '120–180 cm',
  width: '80–100 cm',
  habit: 'Brede bladstelen, artisjok-achtig',
  spacing: '80–100 cm',
  row: '100 cm',
  first: '±150–180 dagen',
  period: 'september – november',
  yield_detail: 'Gebleekte bladstelen; 1 plant levert een stevige bundel',
  points: [
    'Bleken voor milde smaak',
    'Veel ruimte',
    'Najaarsoogst',
    'Rijke grond',
  ],
  summary:
    'Kardoen lijkt op artisjok maar je eet de gebleekte bladstelen. Geef ruimte en bleek 2–3 weken vóór de oogst.',
  know: 'Zonder bleken blijven de stelen bitter en taai.',
});

add('bleekselderij', {
  sow: [2, 3],
  plant: [5, 6],
  harvest: [8, 9, 10, 11],
  standplaats: 'Zon',
  water: 'Hoog',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Hoog',
  height: '40–60 cm',
  width: '25–35 cm',
  habit: 'Bleekbare stengels',
  spacing: '25–30 cm',
  row: '40 cm',
  first: '±120–150 dagen',
  period: 'augustus – november',
  yield_detail: '1 krop bleekselderij per plant; bleken voor mildere smaak',
  points: [
    'Veel water',
    'Voorzaaien vroeg',
    'Bleken optioneel',
    'Niet laten uitdrogen',
  ],
  summary:
    'Bleekselderij vraagt een lang, vochtig groeiseizoen. Voorzaaien en na de vorst uitplanten; houd de grond steeds vochtig.',
  know: 'Droogtestress geeft holle, bittere stengels.',
});

add('bleekselderij_blad', {
  sow: [3, 4, 5, 6],
  plant: [4, 5, 6],
  harvest: [6, 7, 8, 9, 10],
  standplaats: 'Halfschaduw',
  water: 'Hoog',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Pot / Bed',
  voeding: 'Gemiddeld',
  height: '30–45 cm',
  width: '20–30 cm',
  habit: 'Snijselderij / bladselderij',
  spacing: '15–20 cm',
  row: '30 cm',
  first: '±60–80 dagen',
  period: 'juni – oktober',
  yield_level: 'Hoge opbrengst',
  yield_detail: 'Blad voor blad oogsten; sneller dan bleekselderij',
  points: [
    'Makkelijker dan bleekselderij',
    'Doorzaaien mogelijk',
    'Vochtig houden',
    'Potgeschikt',
  ],
  summary:
    'Bladselderij oogst je als aromatisch snijkruid. Sneller en makkelijker dan bleekselderij, ideaal voor soep en salade.',
  know: 'Buitenste bladeren eerst knippen zodat het hart doorgroeit.',
});

add('stengelselderij', {
  sow: [2, 3],
  plant: [5, 6],
  harvest: [8, 9, 10],
  standplaats: 'Zon',
  water: 'Hoog',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Hoog',
  height: '40–60 cm',
  width: '25–35 cm',
  habit: 'Stengel-selderij (bleekselderij-type)',
  spacing: '25–30 cm',
  row: '40 cm',
  first: '±120–150 dagen',
  period: 'augustus – oktober',
  yield_detail: 'Stevige stengels per plant; zelfde teelt als bleekselderij',
  points: [
    'Lang seizoen',
    'Veel vocht',
    'Rijke grond',
    'Uitplanten na vorst',
  ],
  summary:
    'Stengelselderij is de klassieke selderij met eetbare stengels. Teelt als bleekselderij: vroeg voorzaaien en nooit laten uitdrogen.',
  know: 'Zelfblekende rassen besparen het aanaarden of inpakken.',
});

add('knolselerij', {
  sow: [2, 3],
  plant: [5, 6],
  harvest: [9, 10, 11],
  standplaats: 'Zon',
  water: 'Hoog',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Hoog',
  height: '40–60 cm',
  width: '30–40 cm',
  habit: 'Ondergrondse knol met blad',
  spacing: '30–35 cm',
  row: '40–45 cm',
  first: '±150–180 dagen',
  period: 'september – november',
  yield_detail: '1 knol per plant; 800 g–1,5 kg bij goede groei',
  points: [
    'Lang groeiseizoen',
    'Voorzaaien vroeg',
    'Vochtig houden',
    'Blad ook bruikbaar',
  ],
  summary:
    'Knolselderij heeft een heel seizoen nodig. Voorzaaien in februari–maart en uitplanten na de vorst op vochtige, rijke grond.',
  know: 'Oogst vóór strenge vorst; knollen bewaren koel en vochtig.',
});

add('venkel', {
  sow: [4, 5, 6, 7],
  plant: [5, 6, 7],
  harvest: [7, 8, 9, 10],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Gemiddeld',
  height: '50–80 cm',
  width: '30–40 cm',
  habit: 'Knolvenkel / bolvenkel',
  spacing: '25–30 cm',
  row: '40 cm',
  first: '±80–100 dagen',
  period: 'juli – oktober',
  yield_detail: '1 bol per plant; zomerhitte kan doorschieten geven',
  points: [
    'Niet te vroeg zaaien',
    'Gelijkmatig vochtig',
    'Hitte = doorschieten',
    'Anijsachtige smaak',
  ],
  summary:
    'Venkel (knolvenkel) vormt een knapperige bol. Zaai niet te vroeg in het seizoen om doorschieten te voorkomen.',
  know: 'Bij hitte aanaarden en water geven helpt tegen vroeg doorschieten.',
});

add('knolvenkel', {
  sow: [4, 5, 6, 7],
  plant: [5, 6, 7],
  harvest: [7, 8, 9, 10],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Gemiddeld',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Gemiddeld',
  height: '50–80 cm',
  width: '30–40 cm',
  habit: 'Bolvormende knolvenkel',
  spacing: '25–30 cm',
  row: '40 cm',
  first: '±80–100 dagen',
  period: 'juli – oktober',
  yield_detail: 'Stevige witte bollen; 1 per plant na uitdunnen',
  points: [
    'Zomer/najaarsteelt',
    'Niet laten verdrogen',
    'Dunnen op tijd',
    'Doorschieten vermijden',
  ],
  summary:
    'Knolvenkel is de bolvormige venkel voor de keuken. Beste resultaten bij zomer- en najaarszaai met gelijkmatig vocht.',
  know: 'Verwar niet met kruidvenkel, die vooral blad en zaad geeft.',
});

add('knolraap', {
  sow: [3, 4, 7, 8],
  plant: [],
  harvest: [5, 6, 9, 10, 11],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Laag',
  height: '30–45 cm',
  width: '15–25 cm',
  habit: 'Snelle knolgewas',
  spacing: '10–15 cm',
  row: '25–30 cm',
  first: '±40–60 dagen',
  period: 'mei – juni en september – november',
  yield_level: 'Hoge opbrengst',
  yield_detail: 'Jonge knollen; doorzaaien in voor- en najaar',
  points: [
    'Snel',
    'Koel weer beter',
    'Doorzaaien',
    'Niet te dik zaaien',
  ],
  summary:
    'Knolraap groeit snel in koel weer. Zaai in voorjaar en nazomer voor milde, knapperige knollen.',
  know: 'In volle zomerhitte worden knollen houtig of schieten ze door.',
});

add('meiraap', {
  sow: [3, 4, 7, 8],
  plant: [],
  harvest: [5, 6, 9, 10],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Laag',
  height: '25–40 cm',
  width: '10–20 cm',
  habit: 'Vroege kleine raap',
  spacing: '8–12 cm',
  row: '20–25 cm',
  first: '±35–50 dagen',
  period: 'mei – juni en september – oktober',
  yield_level: 'Hoge opbrengst',
  yield_detail: 'Kleine milde rapen; oogst jong',
  points: [
    'Zeer snel',
    'Jong oogsten',
    'Voor- en najaar',
    'Beginnersvriendelijk',
  ],
  summary:
    'Meiraap is een snelle, milde raap voor voorjaar en najaar. Oogst klein voor de beste textuur.',
  know: 'Ideal als tussenteelt tussen langzamere gewassen.',
});

add('raap', {
  sow: [3, 4, 7, 8],
  plant: [],
  harvest: [5, 6, 9, 10, 11],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Laag',
  height: '30–50 cm',
  width: '15–25 cm',
  habit: 'Klassieke raapknol',
  spacing: '10–15 cm',
  row: '25–30 cm',
  first: '±45–70 dagen',
  period: 'mei – juni en september – november',
  yield_detail: 'Ronde of platte knollen; blad ook eetbaar',
  points: [
    'Koel seizoen',
    'Blad én knol',
    'Doorzaaien',
    'Losse grond',
  ],
  summary:
    'Raap is een klassieke knolgewas voor koel weer. Zaai in voorjaar of nazomer en gebruik ook het jonge blad.',
  know: 'Te late oogst geeft grove, pithy knollen.',
});

add('tuinmelde', {
  sow: [3, 4, 5, 6, 7, 8],
  plant: [],
  harvest: [5, 6, 7, 8, 9],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Pot / Bed',
  voeding: 'Laag',
  height: '40–100 cm',
  width: '25–40 cm',
  habit: 'Spinazie-achtig blad, ook rood',
  spacing: '20–25 cm',
  row: '30 cm',
  first: '±35–50 dagen',
  period: 'mei – september',
  yield_level: 'Hoge opbrengst',
  yield_detail: 'Blad voor blad; hittebestendiger dan spinazie',
  points: [
    'Zomerbladgroente',
    'Makkelijk',
    'Rode of groene rassen',
    'Doorzaaien',
  ],
  summary:
    'Tuinmelde is een makkelijke bladgroente die in de zomer beter doorgaat dan spinazie. Oogst jonge bladeren regelmatig.',
  know: 'Laat niet volledig uitbloeien als je lang blad wilt blijven knippen.',
});

add('waterkers', {
  sow: [3, 4, 5, 8, 9],
  plant: [4, 5, 9],
  harvest: [4, 5, 6, 9, 10, 11],
  standplaats: 'Halfschaduw',
  water: 'Hoog',
  difficulty: 'Gemiddeld',
  lifespan: 'Meerjarig',
  outdoor: 'Buiten',
  container: 'Nat bak / beekrand',
  voeding: 'Gemiddeld',
  height: '15–30 cm',
  width: '20–40 cm',
  habit: 'Vochtminnend blad',
  spacing: '15–20 cm',
  row: '20 cm',
  first: '±40–60 dagen',
  period: 'voorjaar en najaar',
  yield_detail: 'Pittig blad; groeit alleen met constante vochtigheid',
  points: [
    'Zeer natte grond',
    'Koel weer',
    'Pittige smaak',
    'Pot in schaal water',
  ],
  summary:
    'Waterkers eist constante vochtigheid. Teel in een natte bak, beekrand of pot die in een waterschaal staat.',
  know: 'In droge grond schiet waterkers snel door en wordt bitter.',
});

add('winterpostelein', {
  sow: [8, 9, 10],
  plant: [],
  harvest: [10, 11, 12, 1, 2, 3],
  standplaats: 'Halfschaduw',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Laag',
  height: '5–15 cm',
  width: '15–25 cm',
  habit: 'Lage winterbladgroente',
  spacing: '10 cm',
  row: '15 cm',
  first: '±40–60 dagen',
  period: 'oktober – maart',
  yield_level: 'Gemiddelde opbrengst',
  yield_detail: 'Mals winterblad; oogst tot het voorjaar',
  points: [
    'Najaar zaaien',
    'Winteroogst',
    'Koudebestendig',
    'Laagblijvend',
  ],
  summary:
    'Winterpostelein zaai je in nazomer/najaar voor verse bladgroente in de koude maanden. Heel anders dan zomerpostelein.',
  know: 'Dekken met vliesdoek verbetert de kwaliteit bij strenge vorst.',
});

add('patisson_geel', {
  sow: [4, 5],
  plant: [5, 6],
  harvest: [7, 8, 9, 10],
  standplaats: 'Zon',
  water: 'Hoog',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Grote bak',
  voeding: 'Hoog',
  height: '40–60 cm',
  width: '80–120 cm',
  habit: 'Gele schijfvormige courgette-achtige',
  spacing: '80–100 cm',
  row: '100–120 cm',
  first: '±50–65 dagen',
  period: 'juli – oktober',
  yield_level: 'Hoge opbrengst',
  yield_detail: 'Gele patissons; jong plukken voor malse vruchten',
  points: [
    'Jong oogsten',
    'Veel ruimte',
    'Warmte',
    'Productief',
  ],
  summary:
    'Gele patisson teel je als courgette: warmte, ruimte en vaak jong plukken voor de beste kwaliteit.',
  know: 'Grote gele patissons worden snel hard; blijf klein oogsten.',
});

add('blauwe_regen_bes', {
  sow: [],
  plant: [3, 4, 10, 11],
  harvest: [7, 8, 9],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Gemiddeld',
  lifespan: 'Meerjarig',
  outdoor: 'Buiten',
  container: 'Bed / Pot',
  voeding: 'Gemiddeld',
  height: '150–250 cm',
  width: '100–150 cm',
  habit: 'Meerjarige besstruik',
  spacing: '100–150 cm',
  row: '150 cm',
  first: 'vanaf 2e–3e jaar',
  period: 'juli – september',
  yield_detail: 'Bessen na vestiging; netten tegen vogels aanbevolen',
  points: [
    'Meerjarig',
    'Zonnige plek',
    'Vogelnet',
    'Snoei na oogst',
  ],
  summary:
    'Blauwe regen-bes is een meerjarige besstruik voor een zonnige tuin. Plant in voor- of najaar en bescherm rijpe bessen tegen vogels.',
  know: 'Controleer of je een zelfbestuivend ras hebt of een bestuiver nodig is.',
});

add('erwtensoep_erwt', {
  sow: [2, 3, 4],
  plant: [],
  harvest: [6, 7],
  standplaats: 'Zon',
  water: 'Gemiddeld',
  difficulty: 'Makkelijk',
  lifespan: 'Eenjarig',
  outdoor: 'Buiten',
  container: 'Volle grond',
  voeding: 'Laag',
  height: '80–150 cm',
  width: '20–30 cm',
  habit: 'Doperwt / soeperwt',
  spacing: '5–8 cm',
  row: '40–50 cm',
  first: '±70–90 dagen',
  period: 'juni – juli',
  yield_detail: 'Peulen voor verse erwtensoep; 0,4–0,8 kg per meter',
  points: [
    'Vroeg zaaien',
    'Klimsteun',
    'Koel voorjaar',
    'Peulen uitdoppen',
  ],
  summary:
    'Erwtensoep-erwt is een klassieke doperwt voor verse soep. Zaai vroeg en geef steun; oogst vóór de peulen taai worden.',
  know: 'Voor wintervoorraad peulen laten opdrogen aan de plant en daarna uitdorsen.',
});

const ids = [
  'artisjok',
  'kardoen',
  'bleekselderij',
  'bleekselderij_blad',
  'stengelselderij',
  'knolselerij',
  'venkel',
  'knolvenkel',
  'knolraap',
  'meiraap',
  'raap',
  'tuinmelde',
  'waterkers',
  'winterpostelein',
  'patisson_geel',
  'blauwe_regen_bes',
  'erwtensoep_erwt',
];
const missing = ids.filter((id) => !j[id]);
fs.writeFileSync(jsonPath, JSON.stringify(j, null, 2) + '\n');
console.log('JSON total', Object.keys(j).length);
console.log('Added/present 17:', ids.every((id) => j[id]));
console.log('Still missing:', missing);
