import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_IN = path.join(__dirname, 'vegetable_overview_all.json');

const NEW_IDS = `
aardbei aardbei_everbearer abrikoos anijs_kruid appel avocado basilicum bieslook blauwe_bes
bonen_sperzie bonenkruid braam bruine_boon citroenboom citroengras citroenmelisse dille doperwt
dragon druif duindoorn estragon framboos gember granaatappel haricots_verts hazelnoot jostabes kaki
kamille kapucijner kastanje_boom kerrieblad kers kervel kikkererwt kiwi komatsuna koriander kriek
kweepeer limoen majoraan mandarijn mango meloen mirabel mispel mizuna mosterdgroen munt nashi_peer
nectarine oregano peer pepermunt perzik peterselie peultjes physalis pinda pruim rode_bes rozemarijn
salie snijbonen snijboon_geel sojaboon sugarsnaps tatsoi tauge tijm tuin_linzen tuinboon tuinerwt
tuinkruid veenbes vijg vlierbes walnoot watermeloen witte_boon zure_kers zwarte_bes
`.trim().split(/\s+/);

function herbAnnual(id, extra = {}) {
  return {
    sow: [3, 4, 5, 6],
    plant: [],
    harvest: [6, 7, 8, 9],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Makkelijk',
    lifespan: 'Eenjarig',
    outdoor: 'Buiten',
    container: 'Pot / Bed',
    voeding: 'Laag',
    height: '20–40 cm',
    width: '20–30 cm',
    habit: 'Bladkruid',
    spacing: '20–25 cm',
    row: '25–30 cm',
    first: '±40–60 dagen',
    period: 'juni – september',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Regelmatig blad knippen voor doorlopende oogst',
    points: ['Warm houden', 'Bloei uitknippen', 'Ochtend oogsten', 'Pot op terras'],
    summary: 'Aromatisch keukenkruid voor de moestuin of pot op een warme plek.',
    know: 'Regelmatig toppen geeft compacter blad en langere oogst.',
    ...extra,
  };
}

function herbPerennial(id, extra = {}) {
  return {
    sow: [3, 4],
    plant: [3, 4, 5],
    harvest: [5, 6, 7, 8, 9, 10],
    standplaats: 'Zon',
    water: 'Laag',
    difficulty: 'Makkelijk',
    lifespan: 'Meerjarig',
    outdoor: 'Buiten',
    container: 'Pot / Bed',
    voeding: 'Laag',
    height: '30–60 cm',
    width: '30–50 cm',
    habit: 'Struikachtig kruid',
    spacing: '30–40 cm',
    row: '40 cm',
    first: 'vanaf 1e jaar',
    period: 'mei – oktober',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Meerjarig; knip takken boven houtige basis',
    points: ['Meerjarig', 'Zon en drainage', 'Snoei na bloei', 'Winterhard'],
    summary: 'Meerjarig Mediterranees kruid dat jarenlang blad levert in een zonnige tuin.',
    know: 'Plant op een doorlatende plek; te natte wintergrond is funest.',
    ...extra,
  };
}

function fruitTree(extra = {}) {
  return {
    sow: [],
    plant: [3, 4, 10, 11],
    harvest: [8, 9, 10],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Gemiddeld',
    lifespan: 'Meerjarig',
    outdoor: 'Buiten',
    container: 'Volle grond',
    voeding: 'Gemiddeld',
    height: '200–400 cm',
    width: '200–350 cm',
    habit: 'Fruitboom',
    spacing: '300–400 cm',
    row: '400 cm',
    first: 'vanaf 2–3 jaar',
    period: 'augustus – oktober',
    yield_level: 'Hoge opbrengst',
    yield_detail: 'Jaarlijkse oogst na vestiging; snoei en bemesting nodig',
    points: ['Plant in rustperiode', 'Jaarlijks snoeien', 'Bestuiving checken', 'Volle zon'],
    summary: 'Klassieke fruitboom voor de Nederlandse tuin; plant in voorjaar of herfst.',
    know: 'Kies een ras dat past bij jouw regio en bestuivers in de buurt.',
    ...extra,
  };
}

function berry(extra = {}) {
  return {
    sow: [],
    plant: [3, 4, 10, 11],
    harvest: [6, 7, 8, 9],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Makkelijk',
    lifespan: 'Meerjarig',
    outdoor: 'Buiten',
    container: 'Bed / Pot',
    voeding: 'Gemiddeld',
    height: '80–150 cm',
    width: '60–120 cm',
    habit: 'Struik of rank',
    spacing: '50–120 cm',
    row: '150 cm',
    first: 'vanaf 1–2 jaar',
    period: 'juni – september',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Meerjarige struik; oogst neemt toe na vestiging',
    points: ['Meerjarig', 'Zon en voeding', 'Snoei na oogst', 'Vogelnet bij rijping'],
    summary: 'Meerjarige bessenstruik voor jarenlang fruit in de tuin.',
    know: 'Snoei oude takken weg voor betere luchtcirculatie en oogst.',
    ...extra,
  };
}

function peaBean(sow, harvest, extra = {}) {
  return {
    sow,
    plant: [],
    harvest,
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Makkelijk',
    lifespan: 'Eenjarig',
    outdoor: 'Buiten',
    container: 'Bed / Pot',
    voeding: 'Laag',
    height: '60–180 cm',
    width: '20–40 cm',
    habit: 'Rankende peulvrucht',
    spacing: '10–15 cm',
    row: '40–60 cm',
    first: '±60–90 dagen',
    period: 'juni – september',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Regelmatig plukken stimuleert nieuwe peulen',
    points: ['Direct zaaien', 'Steun voor rankers', 'Vroeg zaaien', 'Stikstoffixerend'],
    summary: 'Peulgewas voor de moestuin; zaai vroeg in het voorjaar of na vorst.',
    know: 'Peulen regelmatig oogsten zodat de plant door blijft produceren.',
    ...extra,
  };
}

function asianGreen(extra = {}) {
  return {
    sow: [3, 4, 5, 6, 7, 8],
    plant: [],
    harvest: [4, 5, 6, 7, 8, 9, 10],
    standplaats: 'Halfschaduw',
    water: 'Gemiddeld',
    difficulty: 'Makkelijk',
    lifespan: 'Eenjarig',
    outdoor: 'Buiten',
    container: 'Bed / Pot',
    voeding: 'Gemiddeld',
    height: '20–35 cm',
    width: '25–35 cm',
    habit: 'Bladrozet',
    spacing: '20–25 cm',
    row: '30 cm',
    first: '±30–45 dagen',
    period: 'april – oktober',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Snel groeiend blad; meerdere oogsten mogelijk',
    points: ['Koel seizoen', 'Doorzaaien', 'Snel oogstbaar', 'Halfschaduw in zomer'],
    summary: 'Aziatische bladgroente voor koele maanden; zaai in lente en late zomer.',
    know: 'In warme zomer maanden halfschaduw voorkomt doorschieten.',
    ...extra,
  };
}

function tropicalPot(extra = {}) {
  return {
    sow: [3, 4, 5],
    plant: [5, 6, 7, 8],
    harvest: [7, 8, 9, 10],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Moeilijk',
    lifespan: 'Meerjarig',
    outdoor: 'Kas / kuip',
    container: 'Grote pot / kas',
    voeding: 'Gemiddeld',
    height: '150–300 cm',
    width: '100–200 cm',
    habit: 'Pot- of kasplant',
    spacing: '100 cm',
    row: '100 cm',
    first: 'vanaf 3–5 jaar',
    period: 'juli – oktober',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'In NL vooral kas of grote kuip op warm terras',
    points: ['Kas of kuip', 'Winter vorstvrij', 'Veel licht', 'Moeilijk buiten'],
    summary: 'Tropisch fruit dat in Nederland alleen in kas of grote pot opwarmt.',
    know: 'Overwinter vorstvrij binnen of in koele kas met voldoende licht.',
    ...extra,
  };
}

const batch = {
  aardbei: berry({
    plant: [3, 4, 5, 7, 8],
    harvest: [5, 6, 7, 8, 9],
    height: '15–25 cm',
    width: '30–40 cm',
    habit: 'Rosette met runners',
    spacing: '30 cm',
    row: '40 cm',
    first: 'vanaf 1e jaar',
    period: 'mei – september',
    yield_level: 'Hoge opbrengst',
    yield_detail: 'June-bearing; grote oogst in zomer',
    points: ['Meerjarig', 'Mulchen rond rozet', 'Runners verwijderen', 'Vogelnet'],
    summary: 'Klassieke zomeraardbei met één grote oogstpiek. Plant in voorjaar of late zomer.',
    know: 'Verwijder uitlopers in het eerste jaar voor sterkere moederplant.',
  }),
  aardbei_everbearer: berry({
    plant: [3, 4, 5, 7, 8],
    harvest: [5, 6, 7, 8, 9, 10],
    height: '15–25 cm',
    width: '30–40 cm',
    habit: 'Rosette, doorlopende bloei',
    spacing: '30 cm',
    row: '40 cm',
    first: 'vanaf 1e jaar',
    period: 'mei – oktober',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Doorlopende oogst tot late herfst',
    points: ['Doorlopende oogst', 'Regelmatig plukken', 'Mulchen', 'Vogelnet'],
    summary: 'Everbearer geeft fruit van late lente tot herfst. Ideaal voor kleinere tuinen.',
    know: 'Regelmatig oogsten houdt de plant langer productief.',
  }),
  abrikoos: fruitTree({
    harvest: [7, 8],
    difficulty: 'Moeilijk',
    outdoor: 'Beschut / zuidmuur',
    first: 'vanaf 3–4 jaar',
    period: 'juli – augustus',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Vorstgevoelige bloesem; warm en beschut nodig',
    points: ['Warm en beschut', 'Vorstgevoelige bloesem', 'Zuidmuur mogelijk', 'Snoei na oogst'],
    summary: 'Abrikoos vraagt een warme, beschutte plek in NL. Bloesem is gevoelig voor nachtvorst.',
    know: 'Plant op de zuidzijde van een muur voor extra warmte.',
  }),
  anijs_kruid: herbAnnual({
    sow: [4, 5],
    harvest: [7, 8, 9],
    height: '40–60 cm',
    habit: 'Rechtop groeiend kruid',
    first: '±70–90 dagen',
    period: 'juli – september',
    points: ['Direct zaaien', 'Zonnige plek', 'Zaad oogsten', 'Anijssmaak'],
    summary: 'Anijsplant met zoete geur; zaai na vorst in zonnige bedden.',
    know: 'Oogst zaad als schermen bruin kleuren voor kruid en thee.',
  }),
  appel: fruitTree({
    harvest: [8, 9, 10],
    period: 'september – oktober',
    points: ['Plant herfst of voorjaar', 'Jaarlijks snoeien', 'Kies passend ras', 'Volle zon'],
    summary: 'Appelboom is de basis van elke fruittuin. Plant geënte boom in rustperiode.',
    know: 'Veel rassen hebben een bestuiver nodig; check compatibiliteit.',
  }),
  avocado: tropicalPot({
    sow: [3, 4, 5],
    plant: [6, 7, 8],
    harvest: [9, 10],
    height: '200–400 cm',
    habit: 'Bladhoudende kuipplant',
    first: 'zelden in NL',
    period: 'n.v.t. buiten',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Decoratief; vruchten zelden in ons klimaat',
    points: ['Alleen kas/kuip', 'Vorstvrij overwinteren', 'Veel licht', 'Langzaam groeiend'],
    summary: 'Avocado is in NL een kuip- of kasplant. Vruchten zijn zeldzaam buiten tropen.',
    know: 'Pit op water kweken is leuk, maar geënte plant geeft betere kans op vrucht.',
  }),
  basilicum: herbAnnual({
    sow: [3, 4, 5, 6],
    plant: [5, 6, 7],
    difficulty: 'Gemiddeld',
    outdoor: 'Buiten / kas',
    container: 'Pot op warm terras',
    first: '±60–70 dagen',
    points: ['Warm houden', 'Bloei uitknippen', 'Niet onder 12 °C', 'Pot op terras'],
    summary: 'Basilicum is gevoelig voor kou; zaai warm binnen en plant pas na ijsheiligen buiten.',
    know: 'Knip bloemknoppen weg zodat de plant blad blijft maken.',
  }),
  bieslook: herbPerennial({
    sow: [3, 4, 5],
    plant: [3, 4],
    height: '25–40 cm',
    habit: 'Grasachtige pol',
    spacing: '20 cm',
    row: '25 cm',
    points: ['Meerjarig', 'Pol delen', 'Regelmatig snijden', 'Mild ui-aroma'],
    summary: 'Bieslook is meerjarig en groeit in polletjes. Snij regelmatig voor fris blad.',
    know: 'Deel volwassen pol elke paar jaar voor vitaliteit.',
  }),
  blauwe_bes: berry({
    harvest: [7, 8],
    voeding: 'Laag',
    height: '120–180 cm',
    habit: 'Struik, zuurminnend',
    spacing: '120 cm',
    period: 'juli – augustus',
    points: ['Zure grond (pH 4,5–5,5)', 'Twee rassen voor bestuiving', 'Meerjarig', 'Vogelnet'],
    summary: 'Blauwe bes heeft zure, humusrijke grond nodig. Plant minstens twee rassen.',
    know: 'Gebruik turf of speciale potgrond als je grond te kalkrijk is.',
  }),
  bonen_sperzie: peaBean([5, 6], [7, 8, 9], {
    height: '40–60 cm',
    habit: 'Struikboon',
    spacing: '15 cm',
    row: '45 cm',
    first: '±55–70 dagen',
    period: 'juli – september',
    points: ['Na ijsheiligen zaaien', 'Warmteminnend', 'Regelmatig oogsten', 'Stikstoffixerend'],
    summary: 'Sperziebonen zaai je pas na de laatste vorst. Oogst jonge peulen voor malsheid.',
    know: 'Natte peulen zijn taai; pluk elke paar dagen.',
  }),
  bonenkruid: herbPerennial({
    plant: [4, 5],
    height: '40–60 cm',
    habit: 'Halfstruik',
    points: ['Meerjarig', 'Combineert met bonen', 'Zon', 'Snoei in voorjaar'],
    summary: 'Bonenkruid is meerjarig en helpt bonen tegen bladluis. Plant naast peulgewassen.',
    know: 'Staat traditioneel naast tuinbonen en sperziebonen.',
  }),
  braam: berry({
    harvest: [8, 9],
    height: '150–250 cm',
    habit: 'Rankende struik',
    spacing: '80 cm',
    row: '200 cm',
    period: 'augustus – september',
    points: ['Doornloos ras makkelijker', 'Snoei oude scheuten', 'Steun', 'Meerjarig'],
    summary: 'Braam geeft grote zoete bessen in late zomer. Snoei oude takken na oogst.',
    know: 'Doornloze rassen zijn fijner in een kleine tuin.',
  }),
  bruine_boon: peaBean([4, 5], [8, 9], {
    height: '80–120 cm',
    habit: 'Stokboon',
    spacing: '15 cm',
    row: '50 cm',
    first: '±100–120 dagen',
    period: 'augustus – september',
    points: ['Vroeg zaaien', 'Stokken nodig', 'Droog rijp oogsten', 'Winterbewaring'],
    summary: 'Bruine tuinboon voor droge bonen; zaai vroeg en laat peulen rijp drogen.',
    know: 'Oogst als peulen bruin en droog zijn; daarna uittressen.',
  }),
  citroenboom: tropicalPot({
    sow: [],
    plant: [4, 5, 6],
    harvest: [10, 11, 12, 1, 2, 3],
    height: '150–250 cm',
    first: 'vanaf 3–4 jaar',
    period: 'oktober – maart (binnen)',
    points: ['Kas of grote kuip', 'Winter binnen', 'Veel licht', 'Zuurbemesting'],
    summary: 'Citroenboom overwintert binnen of in kas. Geeft geurige vruchten in koele maanden.',
    know: 'Zet in winter op koele, lichte plek; niet te warm anders valt blad af.',
  }),
  citroengras: {
    sow: [3, 4],
    plant: [5, 6],
    harvest: [6, 7, 8, 9, 10],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Gemiddeld',
    lifespan: 'Meerjarig',
    outdoor: 'Kas / kuip',
    container: 'Grote pot / kas',
    voeding: 'Gemiddeld',
    height: '80–120 cm',
    width: '60–80 cm',
    habit: 'Grasachtige pol',
    spacing: '40 cm',
    row: '50 cm',
    first: 'vanaf 1e jaar',
    period: 'juni – oktober',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Stengels voor thee en Aziatische gerechten',
    points: ['Pot in NL', 'Vorstvrij overwinteren', 'Warm en licht', 'Stengels knippen'],
    summary: 'Citroengras groeit in NL het best in pot of kas. Overwinter vorstvrij binnen.',
    know: 'Knip buitenste stengels vlak bij de basis voor de sterkste geur.',
  },
  citroenmelisse: herbPerennial({
    plant: [3, 4],
    height: '60–80 cm',
    habit: 'Geurig blad',
    water: 'Gemiddeld',
    points: ['Meerjarig', 'Citroengeur', 'Thee en salade', 'Kan woekeren'],
    summary: 'Citroenmelisse is meerjarig met frisse citroengeur. Ideaal voor thee en salades.',
    know: 'In pot houden als je woekeren wilt beperken.',
  }),
  dille: herbAnnual({
    sow: [3, 4, 5, 6, 7],
    harvest: [5, 6, 7, 8, 9],
    height: '60–100 cm',
    habit: 'Rechtop scherm',
    first: '±40–50 dagen',
    period: 'mei – september',
    points: ['Direct zaaien', 'Niet verplanten', 'Doorzaaien', 'Scherm voor zaad'],
    summary: 'Dille zaai je direct; wortelstokje maakt verplanten lastig. Doorzaaien voor continue oogst.',
    know: 'Laat een paar planten bloeien voor dillezaad in de keuken.',
  }),
  doperwt: peaBean([2, 3, 4], [6, 7], {
    height: '60–120 cm',
    habit: 'Klimrank',
    spacing: '8 cm',
    row: '45 cm',
    first: '±70–90 dagen',
    period: 'juni – juli',
    points: ['Vroeg in voorjaar', 'Koel starten', 'Trellis nodig', 'Stopt bij hitte'],
    summary: 'Doperwt zaai je vroeg in het voorjaar. Oogst vóór de warme zomerhitte.',
    know: 'In zuid-NL kan een herfstzaai volgende lente vroeg oogst geven.',
  }),
  dragon: herbPerennial({
    sow: [3, 4],
    plant: [4, 5],
    difficulty: 'Gemiddeld',
    height: '60–90 cm',
    habit: 'Slank kruid',
    points: ['Franse dragon via stek', 'Warm en beschut', 'Winter beschermen', 'Voor bloei snijden'],
    summary: 'Dragon is gevoelig voor vorst; Franse dragon via stek, Russische via zaad.',
    know: 'Franse dragon heeft zachte anijssmaak; bescherm in winter.',
  }),
  druif: berry({
    harvest: [9, 10],
    height: '200–300 cm',
    habit: 'Klimrank',
    spacing: '150 cm',
    row: '200 cm',
    period: 'september – oktober',
    points: ['Pergola of muur', 'Winter snoeien', 'Meerjarig', 'Volle zon'],
    summary: 'Druif rankt langs pergola of muur. Snoei in winter voor goede oogst.',
    know: 'Korte knoppen snoeien geeft betere trosvorming.',
  }),
  duindoorn: berry({
    harvest: [9, 10],
    height: '200–400 cm',
    habit: 'Struik of haag',
    spacing: '150 cm',
    period: 'september – oktober',
    points: ['Zon', 'Stikstoffixerend', 'Vogels eten bessen', 'Haag mogelijk'],
    summary: 'Duindoorn geeft oranje bessen rijk aan vitamine C. Plant mannelijke bestuiver erbij.',
    know: 'Eén mannelijke plant bestuift meerdere vrouwelijke struiken.',
  }),
  estragon: herbPerennial({
    plant: [4, 5],
    height: '60–90 cm',
    habit: 'Slank blad',
    difficulty: 'Gemiddeld',
    points: ['Franse estragon via stek', 'Winter beschermen', 'Voor bloei snijden', 'Anijssmaak'],
    summary: 'Estragon (dragon) is gevoelig voor vorst; kweek Franse variant via stek.',
    know: 'Russische estragon uit zaad is minder aromatisch dan Franse stek.',
  }),
  framboos: berry({
    harvest: [7, 8, 9],
    height: '150–200 cm',
    habit: 'Kaneelstokken',
    spacing: '50 cm',
    row: '180 cm',
    period: 'juli – september',
    points: ['Zomer- of herfstframboos', 'Steun latten', 'Snoei oude stokken', 'Meerjarig'],
    summary: 'Framboos geeft zoete bessen op tweejarige stokken. Snoei uitgebloeide takken weg.',
    know: 'Herfstframbozen geven langere oogst dan zomerrassen.',
  }),
  gember: {
    sow: [2, 3, 4],
    plant: [5, 6],
    harvest: [10, 11],
    standplaats: 'Halfschaduw',
    water: 'Gemiddeld',
    difficulty: 'Moeilijk',
    lifespan: 'Eenjarig',
    outdoor: 'Kas / kuip',
    container: 'Grote pot / kas',
    voeding: 'Gemiddeld',
    height: '60–100 cm',
    width: '30–40 cm',
    habit: 'Rhizoom in pot',
    spacing: '25 cm',
    row: '30 cm',
    first: '±8–10 maanden',
    period: 'oktober – november',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Rhizoom oogsten als loof geel wordt',
    points: ['Rhizoom met oog', 'Warm en licht', 'Pot of kas', 'Vorstvrij'],
    summary: 'Gember kweek je in NL in pot of kas van een stuk rhizoom met oog.',
    know: 'Leg rhizoom plat op vochtige potgrond; niet te diep bedekken.',
  },
  granaatappel: tropicalPot({
    sow: [],
    plant: [4, 5],
    harvest: [9, 10],
    height: '150–250 cm',
    points: ['Kas of kuip', 'Warm terras', 'Winter binnen', 'Zeldzaam vruchten in NL'],
    summary: 'Granaatappel is een sierlijke kuipplant; vruchten zijn zeldzaam in ons klimaat.',
    know: 'Houd compact door lichte snoei; veel zon op terras in zomer.',
  }),
  haricots_verts: peaBean([5, 6], [7, 8, 9], {
    height: '40–50 cm',
    habit: 'Struikboon',
    spacing: '15 cm',
    row: '40 cm',
    first: '±55–65 dagen',
    period: 'juli – september',
    points: ['Fijne sperzieboon', 'Na vorst zaaien', 'Regelmatig plukken', 'Mals oogsten'],
    summary: 'Haricots verts zijn dunne sperziebonen; zaai na ijsheiligen en oogst jong.',
    know: 'Pluk peulen als ze nog dun en zonder zaad zijn.',
  }),
  hazelnoot: fruitTree({
    harvest: [9, 10],
    height: '300–500 cm',
    habit: 'Struik of boom',
    spacing: '300 cm',
    period: 'september – oktober',
    points: ['Meerjarig', 'Bestuiving nodig', 'Eekhoorns!', 'Snoei in winter'],
    summary: 'Hazelnoot geeft noten in herfst. Plant meerdere rassen voor bestuiving.',
    know: 'Eekhoorns oogsten sneller dan jij; oogst rijpe noten direct.',
  }),
  jostabes: berry({
    harvest: [7, 8],
    height: '150–200 cm',
    habit: 'Doornige struik',
    spacing: '150 cm',
    period: 'juli – augustus',
    points: ['Kruising bes en kruisbes', 'Zuur en zoet', 'Meerjarig', 'Jam en sap'],
    summary: 'Jostabes combineert smaak van bes en kruisbes. Meerjarige doornige struik.',
    know: 'Bessen zijn rijp als ze diepzwart en zacht zijn.',
  }),
  kaki: fruitTree({
    plant: [3, 4],
    harvest: [10, 11],
    difficulty: 'Moeilijk',
    outdoor: 'Beschut / kuip',
    container: 'Grote pot / beschut',
    height: '250–400 cm',
    period: 'oktober – november',
    yield_level: 'Beperkte opbrengst',
    points: ['Warm microklimaat', 'Pot of zuidmuur', 'Winter beschermen', 'Nazoeten binnen'],
    summary: 'Kaki (persimmon) heeft warmte nodig; in NL vaak in pot op beschutte plek.',
    know: 'Laat niet-wasmijnrassen nazoeten tot ze zacht zijn.',
  }),
  kamille: herbAnnual({
    sow: [3, 4, 5],
    harvest: [6, 7, 8],
    height: '30–50 cm',
    habit: 'Theekruid met bloemen',
    first: '±60–80 dagen',
    period: 'juni – augustus',
    points: ['Direct zaaien', 'Bloemen voor thee', 'Zonnige plek', 'Eenjarig'],
    summary: 'Kamille zaai je in lente voor geurige bloemen voor thee en cosmetica.',
    know: 'Oogst bloemhoofdjes op droge ochtend voor sterkste aroma.',
  }),
  kapucijner: peaBean([2, 3, 4], [6, 7, 8], {
    height: '100–150 cm',
    habit: 'Klimrank met kleurige bloem',
    spacing: '15 cm',
    row: '50 cm',
    first: '±90–110 dagen',
    period: 'juni – augustus',
    points: ['Vroeg zaaien', 'Stokken nodig', 'Paars geurende bloem', 'Droog of groen oogsten'],
    summary: 'Kapucijner is een sierlijke tuinboon met paarse bloemen; zaai vroeg in voorjaar.',
    know: 'Peulen jong eten als groene bonen of rijp drogen voor bewaring.',
  }),
  kastanje_boom: fruitTree({
    harvest: [10],
    height: '800–1500 cm',
    habit: 'Grote boom',
    spacing: '800 cm',
    first: 'vanaf 5–10 jaar',
    period: 'oktober',
    yield_level: 'Hoge opbrengst',
    points: ['Grote boom', 'Lang wachten', 'Vruchten vallen rijp', 'Schimmelgevoelig'],
    summary: 'Kastanjeboom geeft na jaren eetbare kastanjes in oktober. Grote tuin nodig.',
    know: 'Kies een eetbare kastanjesoort, niet paardenkastanje.',
  }),
  kerrieblad: {
    sow: [],
    plant: [5, 6, 7, 8],
    harvest: [6, 7, 8, 9, 10],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Moeilijk',
    lifespan: 'Meerjarig',
    outdoor: 'Kas / kuip',
    container: 'Grote pot / kas',
    voeding: 'Gemiddeld',
    height: '200–400 cm',
    width: '150–200 cm',
    habit: 'Bladhoudende kuipplant',
    spacing: '150 cm',
    row: '150 cm',
    first: 'vanaf 2–3 jaar',
    period: 'juni – oktober',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Blad voor curry; kas in NL',
    points: ['Kas of warm kuip', 'Winter binnen', 'Blad oogsten', 'Tropisch'],
    summary: 'Kerrieblad (curryplant) groeit in NL alleen in kas of warme kuip.',
    know: 'Oogst jonge bladeren; plant is gevoelig voor temperatuur onder 10 °C.',
  },
  kers: fruitTree({
    harvest: [6, 7],
    height: '300–500 cm',
    period: 'juni – juli',
    points: ['Beschut tegen regen', 'Vogelnet', 'Snoeien zomer', 'Volle zon'],
    summary: 'Zoete kers bloeit vroeg; beschut tegen nachtvorst en regen bij bloei.',
    know: 'Net over boom bij rijping voorkomt vogelschade.',
  }),
  kervel: herbAnnual({
    sow: [3, 4, 5, 6, 7, 8],
    harvest: [4, 5, 6, 7, 8, 9],
    height: '30–60 cm',
    first: '±40–50 dagen',
    period: 'april – september',
    points: ['Direct zaaien', 'Niet verplanten', 'Doorzaaien', 'Fijne anijssmaak'],
    summary: 'Kervel kiemt snel en groeit fijne bladeren; zaai direct en doorzaai regelmatig.',
    know: 'Jong blad heeft de beste smaak; niet te lang laten staan.',
  }),
  kikkererwt: peaBean([3, 4, 5], [7, 8, 9], {
    height: '50–70 cm',
    habit: 'Struikachtig',
    spacing: '15 cm',
    row: '40 cm',
    first: '±90–100 dagen',
    period: 'juli – september',
    points: ['Warm zaaien', 'Droog rijp oogsten', 'Koken en pureren', 'Stikstoffixerend'],
    summary: 'Kikkererwt zaai je in warme lente; oogst droge peulen voor koken.',
    know: 'Laat peulen volledig drogen aan plant voor bewaring.',
  }),
  kiwi: berry({
    plant: [3, 4],
    harvest: [10, 11],
    height: '300–500 cm',
    habit: 'Klimrank',
    spacing: '300 cm',
    difficulty: 'Gemiddeld',
    period: 'oktober – november',
    points: ['Mannelijke én vrouwelijke plant', 'Pergola of muur', 'Snoei in winter', 'Nazoeten binnen'],
    summary: 'Kiwi rankt en heeft mannelijke én vrouwelijke plant nodig voor vruchten.',
    know: 'Vruchten rijpen af na pluk op een koele plek.',
  }),
  komatsuna: asianGreen({
    points: ['Japanse mosterd', 'Koel seizoen', 'Snel oogstbaar', 'Rauw of gewokt'],
    summary: 'Komatsuna is Japanse bladmosterd; zaai in koele maanden voor zacht blad.',
    know: 'Oogst blad als rozet nog jong is voor de beste textuur.',
  }),
  koriander: herbAnnual({
    sow: [4, 5, 6, 7, 8],
    harvest: [5, 6, 7, 8, 9, 10],
    standplaats: 'Halfschaduw',
    first: '±40–50 dagen',
    period: 'mei – oktober',
    points: ['Doorzaaien elke 3 weken', 'Halfschaduw tegen doorschieten', 'Blad én zaad', 'Hitte = bloei'],
    summary: 'Koriander schiet door in hitte; zaai regelmatig en kies halfschaduw in zomer.',
    know: 'Laat een paar planten zaad geven voor korianderzaad in de keuken.',
  }),
  kriek: fruitTree({
    harvest: [6, 7],
    period: 'juni – juli',
    points: ['Zure kers variant', 'Jam en sap', 'Vroeg oogsten', 'Kleinere boom'],
    summary: 'Kriek is een zure kers voor jam en likeur. Oogst in vroege zomer.',
    know: 'Bessen zijn rijp als ze dieprood en loslatend zijn.',
  }),
  kweepeer: fruitTree({
    harvest: [9, 10],
    period: 'september – oktober',
    points: ['Hard vruchtvlees', 'Lang rijp bewaren', 'Zelfbestuivend', 'Compacter dan peer'],
    summary: 'Kweepeer geeft aromatisch hard fruit dat lang rijp kan worden bewaard.',
    know: 'Laat vruchten na pluk rijpen op kamertemperatuur.',
  }),
  limoen: tropicalPot({
    sow: [],
    plant: [4, 5, 6],
    harvest: [10, 11, 12, 1, 2],
    points: ['Kas of kuip', 'Winter binnen', 'Veel licht', 'Zure vruchten'],
    summary: 'Limoenboom is een kuipplant voor kas of binnen; geeft zure vruchten in winter.',
    know: 'Houd vochtig maar niet nat in winter op koele lichte plek.',
  }),
  majoraan: {
    sow: [3, 4],
    plant: [5, 6],
    harvest: [6, 7, 8, 9],
    standplaats: 'Zon',
    water: 'Laag',
    difficulty: 'Gemiddeld',
    lifespan: 'Tweejarig',
    outdoor: 'Buiten / kas',
    container: 'Pot op terras',
    voeding: 'Laag',
    height: '30–50 cm',
    width: '30–40 cm',
    habit: 'Laag kruid',
    spacing: '25 cm',
    row: '30 cm',
    first: '±60–70 dagen',
    period: 'juni – september',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Gevoelig voor vorst; pot of kas overwinteren',
    points: ['Vorstgevoelig', 'Pot overwinteren', 'Voor bloei snijden', 'Zonnige plek'],
    summary: 'Majoraan is gevoelig voor vorst; kweek in pot en zet vorstvrij overwinteren.',
    know: 'Oogst vóór bloei voor de sterkste smaak.',
  },
  mandarijn: tropicalPot({
    sow: [],
    plant: [4, 5, 6],
    harvest: [11, 12, 1],
    points: ['Kas of kuip', 'Winter binnen', 'Zoete vruchten', 'Veel zon'],
    summary: 'Mandarijnboom overwintert binnen; geeft kleine zoete vruchten in winter.',
    know: 'Zet in winter op koele lichte plek; niet te warm.',
  }),
  mango: tropicalPot({
    sow: [3, 4, 5],
    plant: [6, 7, 8],
    harvest: [7, 8, 9],
    height: '200–400 cm',
    points: ['Alleen kas/kuip', 'Min. 18 °C', 'Langzaam groeiend', 'Vruchten zeldzaam'],
    summary: 'Mango is in NL een kas- of kuipplant; vruchten zijn zeldzaam buiten tropen.',
    know: 'Geënte plant heeft meer kans op vrucht dan pit uit supermarkt.',
  }),
  meloen: {
    sow: [4, 5],
    plant: [5, 6],
    harvest: [8, 9],
    standplaats: 'Zon',
    water: 'Hoog',
    difficulty: 'Moeilijk',
    lifespan: 'Eenjarig',
    outdoor: 'Kas / kuip',
    container: 'Kas / grote pot',
    voeding: 'Hoog',
    height: '30–50 cm',
    width: '150–200 cm',
    habit: 'Kruipend rank',
    spacing: '80 cm',
    row: '120 cm',
    first: '±80–100 dagen',
    period: 'augustus – september',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Warmte en kas nodig in NL',
    points: ['Voorzaaien in kas', 'Veel warmte', 'Gelijkmatig water', 'Moeilijk buiten'],
    summary: 'Meloen vraagt kas en warmte in NL; voorzaai in april en oogst in late zomer.',
    know: 'Geur bij het klokje en loslatende stengel wijzen op rijpheid.',
  },
  mirabel: fruitTree({
    harvest: [7, 8],
    height: '300–400 cm',
    period: 'juli – augustus',
    points: ['Kleine gele pruim', 'Jam en compote', 'Zelfbestuivend', 'Compacte boom'],
    summary: 'Mirabel is een kleine gele pruim voor jam. Oogst in midzomer.',
    know: 'Oogst als vruchten loslaten van de tak.',
  }),
  mispel: fruitTree({
    harvest: [10, 11],
    period: 'oktober – november',
    points: ['Hard fruit', 'Na vorst zoeter', 'Lang rijp bewaren', 'Zeldzaam in NL'],
    summary: 'Mispel geeft hard herfstfruit dat na lichte vorst zoeter wordt.',
    know: 'Laat vruchten rijpen tot ze zacht zijn na een koude nacht.',
  }),
  mizuna: asianGreen({
    points: ['Fijn gesneden blad', 'Koel seizoen', 'Salade en wok', 'Snel groeiend'],
    summary: 'Mizuna is fijn blad voor salade; zaai in koele maanden voor beste kwaliteit.',
    know: 'Snij blad boven grond; plant loopt opnieuw uit.',
  }),
  mosterdgroen: asianGreen({
    height: '40–60 cm',
    habit: 'Pittig blad',
    points: ['Pittig blad', 'Koel seizoen', 'Salade en roerbak', 'Snel oogstbaar'],
    summary: 'Mosterdgroen geeft pittig blad; teelt als andere Aziatische bladgroenten.',
    know: 'Jong blad is milder; ouder blad wordt scherper.',
  }),
  munt: herbPerennial({
    plant: [3, 4],
    height: '30–60 cm',
    habit: 'Woekerend kruid',
    container: 'Pot (woekert)',
    water: 'Hoog',
    points: ['Meerjarig', 'Woekert — pot!', 'Vochtige grond', 'Thee en cocktails'],
    summary: 'Munt is meerjarig en woekert; kweek altijd in pot om uitbreiding te beperken.',
    know: 'Pot half begraven voorkomt dat wortels onder de pot uitlopen.',
  }),
  nashi_peer: fruitTree({
    harvest: [9, 10],
    difficulty: 'Gemiddeld',
    period: 'september – oktober',
    points: ['Aziatische peer', 'Knapperig vruchtvlees', 'Bestuiving nodig', 'Beschut'],
    summary: 'Nashi-peer geeft knapperige Aziatische peren in herfst. Plant beschut.',
    know: 'Oogst als vrucht hard maar rijp van kleur is; eet knapperig.',
  }),
  nectarine: fruitTree({
    harvest: [7, 8],
    period: 'juli – augustus',
    points: ['Gladde variant perzik', 'Warm en beschut', 'Snoei na oogst', 'Vorstgevoelig'],
    summary: 'Nectarine is een gladde perzik; vraagt warme, beschutte plek in NL.',
    know: 'Bescherm bloesem tegen late nachtvorst met vliesdoek.',
  }),
  oregano: herbPerennial({
    sow: [3, 4],
    plant: [5, 6],
    points: ['Meerjarig', 'Mediterrane grond', 'Voor bloei snijden', 'Winterhard'],
    summary: 'Oregano is winterhard Mediterraans kruid; plant op droge, zonnige plek.',
    know: 'Smaak is sterkst vlak vóór bloei.',
  }),
  peer: fruitTree({
    harvest: [8, 9, 10],
    period: 'augustus – oktober',
    points: ['Plant herfst/voorjaar', 'Kruisbestuiving', 'Jaarlijks snoeien', 'Volle zon'],
    summary: 'Peer is klassiek boomfruit; kies ras met passende bestuivers.',
    know: 'Sommige rassen oogst je hard en laat je rijpen binnen.',
  }),
  pepermunt: herbPerennial({
    plant: [3, 4],
    height: '30–50 cm',
    container: 'Pot (woekert)',
    water: 'Hoog',
    points: ['Meerjarig', 'Sterkere munt', 'Pot tegen woekeren', 'Thee'],
    summary: 'Pepermunt is sterker dan gewone munt; kweek in pot tegen woekeren.',
    know: 'Verschil met munt: pepermunt heeft sterker menthol-aroma.',
  }),
  perzik: fruitTree({
    harvest: [7, 8],
    difficulty: 'Gemiddeld',
    period: 'juli – augustus',
    points: ['Muur- of leiboom', 'Warm en beschut', 'Snoei na oogst', 'Vorstgevoelig'],
    summary: 'Perzik bloeit vroeg en vraagt beschutting; leiboom op zuidmuur werkt goed.',
    know: 'Snoei na oogst licht voor open kroon.',
  }),
  peterselie: {
    sow: [3, 4, 5],
    plant: [],
    harvest: [5, 6, 7, 8, 9, 10, 11],
    standplaats: 'Halfschaduw',
    water: 'Gemiddeld',
    difficulty: 'Gemiddeld',
    lifespan: 'Tweejarig',
    outdoor: 'Buiten',
    container: 'Pot / Bed',
    voeding: 'Gemiddeld',
    height: '25–40 cm',
    width: '20–30 cm',
    habit: 'Bladrozet',
    spacing: '20 cm',
    row: '25 cm',
    first: '±70–90 dagen',
    period: 'mei – november',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Tweejarig; lang oogstbaar blad',
    points: ['Kiemt traag', 'Tweejarig', 'Buitenste bladeren eerst', 'Grond vochtig houden'],
    summary: 'Peterselie is tweejarig en kiemt traag; houd zaad vochtig tot kiem.',
    know: 'Week zaad een nacht in water voor snellere kieming.',
  },
  peultjes: peaBean([3, 4], [6, 7], {
    height: '60–80 cm',
    habit: 'Klimrank',
    spacing: '5 cm',
    row: '40 cm',
    first: '±60–70 dagen',
    period: 'juni – juli',
    points: ['Vroeg zaaien', 'Platte peul', 'Regelmatig plukken', 'Klimnet'],
    summary: 'Peultjes zijn platte peulen; zaai vroeg en oogst als peul nog plat is.',
    know: 'Pluk elke paar dagen; oude peulen remmen nieuwe groei.',
  }),
  physalis: {
    sow: [3, 4],
    plant: [5, 6],
    harvest: [8, 9, 10],
    standplaats: 'Zon',
    water: 'Gemiddeld',
    difficulty: 'Gemiddeld',
    lifespan: 'Eenjarig',
    outdoor: 'Kas / kuip',
    container: 'Pot / kas',
    voeding: 'Gemiddeld',
    height: '60–100 cm',
    width: '60–80 cm',
    habit: 'Struik met papieren huls',
    spacing: '50 cm',
    row: '60 cm',
    first: '±100 dagen',
    period: 'augustus – oktober',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Zoete bessen in papieren hulsjes',
    points: ['Voorzaaien warm', 'Kas aanbevolen', 'Warmteminnend', 'Huls bruin = rijp'],
    summary: 'Physalis (kaapse kruisbes) is warmteminnend; kas aanbevolen in NL.',
    know: 'Bessen zijn rijp als papieren huls bruin en bessen geel zijn.',
  },
  pinda: peaBean([5, 6], [9, 10], {
    height: '30–40 cm',
    habit: 'Grondpen',
    difficulty: 'Moeilijk',
    spacing: '25 cm',
    row: '50 cm',
    first: '±120–140 dagen',
    period: 'september – oktober',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Warm zomer nodig; moeilijk in koele zomer',
    points: ['Warm zomer nodig', 'Grond los maken', 'Oogst met vork', 'Moeilijk in NL'],
    summary: 'Pinda vraagt een warme zomer; in NL moeilijk maar mogelijk op zuidelijke plek.',
    know: 'Grond los maken vóór zaaien; oogst met vork als blad geel wordt.',
  }),
  pruim: fruitTree({
    harvest: [8, 9],
    period: 'augustus – september',
    points: ['Plant herfst/voorjaar', 'Veel rassen', 'Snoei na oogst', 'Jam en vers'],
    summary: 'Pruimenboom geeft zoet fruit in late zomer. Plant in rustperiode.',
    know: 'Oogst als vrucht zacht aanvoelt en loslaat.',
  }),
  rode_bes: berry({
    harvest: [6, 7, 8],
    height: '120–150 cm',
    period: 'juni – augustus',
    points: ['Koeler klimaat', 'Snoei na oogst', 'Trossen oogsten', 'Meerjarig'],
    summary: 'Rode bes groeit goed in koeler klimaat; snoei oude takken na oogst.',
    know: 'Oogst hele trossen; bessen losmaken na pluk.',
  }),
  rozemarijn: herbPerennial({
    plant: [5, 6],
    difficulty: 'Gemiddeld',
    height: '80–120 cm',
    outdoor: 'Buiten / beschut',
    points: ['Meerjarig', 'Beschut of zuidmuur', 'Droge grond', 'Winter beschermen'],
    summary: 'Rozemarijn is winterhard maar profiteert van beschutte zuidplek in NL.',
    know: 'Plant op doorlatende grond; natte wintergrond is dodelijk.',
  }),
  salie: herbPerennial({
    plant: [5],
    height: '40–60 cm',
    points: ['Meerjarig', 'Winterhard', 'Voor bloei snijden', 'Medicinaal en keuken'],
    summary: 'Salie is winterhard Mediterraans kruid met zilvergroen blad.',
    know: 'Snoei na bloei licht terug voor compacte groei.',
  }),
  snijbonen: peaBean([5, 6], [7, 8, 9], {
    height: '180–250 cm',
    habit: 'Stokboon',
    spacing: '15 cm',
    row: '50 cm',
    points: ['Na vorst zaaien', 'Hoge stokken', 'Regelmatig oogsten', 'Warmteminnend'],
    summary: 'Snijbonen zijn hoge stokbonen; zaai na ijsheiligen en geef stevige stokken.',
    know: 'Wind kan stokken omblazen; stevig afbinden aan stokken.',
  }),
  snijboon_geel: peaBean([5, 6], [7, 8, 9], {
    height: '180–250 cm',
    habit: 'Gele stokboon',
    spacing: '15 cm',
    row: '50 cm',
    points: ['Gele peul', 'Stokken nodig', 'Na vorst', 'Mals oogsten'],
    summary: 'Gele snijboon is een stokboon met gele peul; zelfde teelt als groene variant.',
    know: 'Oogst peulen jong; geel blijft mals bij regelmatig plukken.',
  }),
  sojaboon: peaBean([5, 6], [9, 10], {
    height: '60–80 cm',
    habit: 'Struikboon',
    spacing: '20 cm',
    row: '50 cm',
    first: '±100–110 dagen',
    period: 'september – oktober',
    points: ['Warm zaaien', 'Edamame', 'Groen oogsten', 'Stikstoffixerend'],
    summary: 'Sojaboon (edamame) zaai je warm; oogst peulen groen voor koken.',
    know: 'Kook peulen kort in gezouten water als edamame.',
  }),
  sugarsnaps: peaBean([3, 4], [6, 7], {
    height: '150–180 cm',
    habit: 'Klimpeul',
    spacing: '5 cm',
    row: '40 cm',
    first: '±60–75 dagen',
    period: 'juni – juli',
    points: ['Eetbare peul', 'Klimnet', 'Vroeg zaaien', 'Zoete smaak'],
    summary: 'Sugarsnaps hebben eetbare peul; zaai vroeg en geef klimsteun.',
    know: 'Pluk als peul nog plat en glanzend is.',
  }),
  tatsoi: asianGreen({
    habit: 'Platte rozet',
    points: ['Platte rozet', 'Koel seizoen', 'Hele rozet oogstbaar', 'Mild van smaak'],
    summary: 'Tatsoi vormt platte rozetten; zaai in koele maanden voor zacht blad.',
    know: 'Oogst hele jonge rozetten of snij bladeren boven grond.',
  }),
  tauge: {
    sow: [],
    plant: [],
    harvest: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    standplaats: 'Halfschaduw',
    water: 'Gemiddeld',
    difficulty: 'Makkelijk',
    lifespan: 'Eenjarig',
    outdoor: 'Binnen',
    container: 'Pot / kiembak',
    voeding: 'Laag',
    height: '5–10 cm',
    width: '10–15 cm',
    habit: 'Kiemplant',
    spacing: 'n.v.t.',
    row: 'n.v.t.',
    first: '±3–5 dagen',
    period: 'het hele jaar',
    yield_level: 'Gemiddelde opbrengst',
    yield_detail: 'Kiemsalade; geen grond nodig',
    points: ['Kiemsalade', 'Hele jaar binnen', 'Geen zon nodig', 'Snel klaar'],
    summary: 'Tauge (mungoboon) kiem je binnen op vochtig gaas; klaar in enkele dagen.',
    know: 'Spoel kiemende zaden tweemaal daags om schimmel te voorkomen.',
  },
  tijm: herbPerennial({
    plant: [5, 6],
    height: '15–25 cm',
    habit: 'Laag kruipend',
    points: ['Meerjarig', 'Droge grond', 'Winterhard', 'Keuken en bijen'],
    summary: 'Tijm is laag, winterhard kruid voor droge, zonnige plekken.',
    know: 'Snoei na bloei om houtige center te verjongen.',
  }),
  tuin_linzen: peaBean([3, 4], [7, 8], {
    height: '30–40 cm',
    habit: 'Laag struik',
    spacing: '10 cm',
    row: '30 cm',
    first: '±90–100 dagen',
    period: 'juli – augustus',
    points: ['Vroeg zaaien', 'Droog oogsten', 'Stikstoffixerend', 'Soep en stoof'],
    summary: 'Tuinlinzen zaai je vroeg; oogst droge peulen voor linzen.',
    know: 'Maaidors na droging en wierp in de wind om te dorsen.',
  }),
  tuinboon: peaBean([2, 3, 4], [6, 7, 8], {
    height: '80–120 cm',
    habit: 'Stokboon',
    spacing: '15 cm',
    row: '45 cm',
    first: '±90–110 dagen',
    period: 'juni – augustus',
    points: ['Vroeg zaaien', 'Toppen tegen luizen', 'Stokken', 'Koel starten'],
    summary: 'Tuinboon zaai je vroeg in voorjaar; top na eerste peulen tegen zwarte luis.',
    know: 'Top de plant als eerste peulen zetten om luis te beperken.',
  }),
  tuinerwt: peaBean([3, 4], [6, 7], {
    height: '60–80 cm',
    habit: 'Klimrank',
    spacing: '5 cm',
    row: '40 cm',
    first: '±60–70 dagen',
    period: 'juni – juli',
    points: ['Vroeg zaaien', 'Klimnet', 'Vers eten', 'Koel starten'],
    summary: 'Tuinerwt is de klassieke groene erwt; zaai vroeg en oogst vers.',
    know: 'Oogst als peulen goed gevuld maar nog glanzend zijn.',
  }),
  tuinkruid: herbPerennial({
    plant: [4, 5],
    height: '30–50 cm',
    habit: 'Aromatisch blad',
    points: ['Meerjarig (marjolein)', 'Zonnige plek', 'Thee en keuken', 'Winterhard'],
    summary: 'Tuinkruid (marjolein) is meerjarig aromatisch kruid voor keuken en thee.',
    know: 'Verschil met majoraan: tuinkruid is winterharder in NL.',
  }),
  veenbes: berry({
    plant: [3, 4],
    harvest: [8, 9],
    voeding: 'Laag',
    height: '20–40 cm',
    habit: 'Laag zuurminnend',
    spacing: '30 cm',
    row: '40 cm',
    period: 'augustus – september',
    points: ['Zure grond', 'Laag blijvend', 'Meerjarig', 'Snoei in voorjaar'],
    summary: 'Veenbes groeit laag op zure grond; ideaal voor potten met turf.',
    know: 'Gebruik zure potgrond; gewone tuinaarde geeft gele bladeren.',
  }),
  vijg: fruitTree({
    plant: [3, 4],
    harvest: [8, 9],
    difficulty: 'Gemiddeld',
    outdoor: 'Beschut / kas',
    container: 'Pot / zuidmuur',
    height: '200–400 cm',
    period: 'augustus – september',
    points: ['Zuidmuur of kas', 'Winter beschermen', 'Twee oogsten mogelijk', 'Warm'],
    summary: 'Vijg groeit in NL op zuidmuur of in kas; winter beschermen.',
    know: 'Kleine herfstvruchten overwinteren voor vroege oogst volgend jaar.',
  }),
  vlierbes: berry({
    harvest: [8, 9],
    height: '300–500 cm',
    habit: 'Grote struik',
    spacing: '200 cm',
    period: 'augustus – september',
    points: ['Bloesem en bessen', 'Siroop en jam', 'Snoei oud hout', 'Meerjarig'],
    summary: 'Vlier (vlierbes) geeft bloesem en bessen voor siroop; snoei oud hout.',
    know: 'Kook bessen altijd; rauw zijn ze licht giftig.',
  }),
  walnoot: fruitTree({
    harvest: [10],
    height: '800–1200 cm',
    habit: 'Grote boom',
    spacing: '800 cm',
    first: 'vanaf 5–8 jaar',
    period: 'oktober',
    points: ['Grote boom', 'Lang wachten', 'Juglon in blad', 'Noten vallen rijp'],
    summary: 'Walnotenboom geeft na jaren noten in oktober. Grote tuin nodig.',
    know: 'Noten zijn rijp als groene schil scheurt en noten vallen.',
  }),
  watermeloen: {
    sow: [4, 5],
    plant: [5, 6],
    harvest: [8, 9],
    standplaats: 'Zon',
    water: 'Hoog',
    difficulty: 'Moeilijk',
    lifespan: 'Eenjarig',
    outdoor: 'Kas / kuip',
    container: 'Kas / grote pot',
    voeding: 'Hoog',
    height: '30–40 cm',
    width: '200–300 cm',
    habit: 'Kruipend rank',
    spacing: '100 cm',
    row: '150 cm',
    first: '±90–120 dagen',
    period: 'augustus – september',
    yield_level: 'Beperkte opbrengst',
    yield_detail: 'Veel warmte; kas in NL',
    points: ['Kas verplicht', 'Veel warmte', 'Veel water', 'Moeilijk buiten'],
    summary: 'Watermeloen vraagt kas en warmte; voorzaai in april op warm.',
    know: 'Kloppen op rijpe vrucht geeft holle klank.',
  },
  witte_boon: peaBean([4, 5], [8, 9], {
    height: '80–120 cm',
    habit: 'Stokboon',
    spacing: '15 cm',
    row: '50 cm',
    first: '±100–120 dagen',
    period: 'augustus – september',
    points: ['Vroeg zaaien', 'Stokken', 'Droog oogsten', 'Bewaring'],
    summary: 'Witte tuinboon voor droge bonen; zelfde teelt als bruine variant.',
    know: 'Oogst als peulen volledig droog en wit zijn.',
  }),
  zure_kers: fruitTree({
    harvest: [6, 7],
    height: '300–500 cm',
    period: 'juni – juli',
    points: ['Zure kers', 'Jam en sap', 'Kleinere boom', 'Vroeg oogsten'],
    summary: 'Zure kers is ideaal voor jam en sap; oogst in vroege zomer.',
    know: 'Bessen loslaten van tak = rijp voor oogst.',
  }),
  zwarte_bes: berry({
    harvest: [7, 8],
    height: '120–150 cm',
    period: 'juli – augustus',
    points: ['Cassis-smaak', 'Jam en sap', 'Meerjarig', 'Snoei na oogst'],
    summary: 'Zwarte bes (cassis) geeft rijke bessen voor jam en sap.',
    know: 'Oogst in clusters als bessen diepzwart en zacht zijn.',
  }),
};

const existing = JSON.parse(fs.readFileSync(JSON_IN, 'utf8'));
const added = [];
const skipped = [];

for (const id of NEW_IDS) {
  if (existing[id]) {
    skipped.push(id);
    continue;
  }
  if (!batch[id]) {
    console.error(`No data for ${id}`);
    process.exit(1);
  }
  existing[id] = batch[id];
  added.push(id);
}

const sorted = Object.fromEntries(Object.keys(existing).sort().map((k) => [k, existing[k]]));
fs.writeFileSync(JSON_IN, JSON.stringify(sorted, null, 2) + '\n', 'utf8');

console.log(`Merged ${added.length} new entries into ${JSON_IN}`);
console.log(`Total keys: ${Object.keys(sorted).length}`);
if (skipped.length) console.log(`Skipped existing: ${skipped.join(', ')}`);
if (added.length !== NEW_IDS.length) {
  console.error(`Expected ${NEW_IDS.length} new, added ${added.length}`);
  process.exit(1);
}
