import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_IN = path.join(__dirname, 'vegetable_overview_all.json');
const OUT = path.join(__dirname, '..', 'lib', 'data', 'vegetable_overview_entries.dart');

const REQUIRED_NEW_IDS = `
aardbei aardbei_everbearer abrikoos anijs_kruid appel avocado basilicum bieslook blauwe_bes
bonen_sperzie bonenkruid braam bruine_boon citroenboom citroengras citroenmelisse dille doperwt
dragon druif duindoorn estragon framboos gember granaatappel haricots_verts hazelnoot jostabes kaki
kamille kapucijner kastanje_boom kerrieblad kers kervel kikkererwt kiwi komatsuna koriander kriek
kweepeer limoen majoraan mandarijn mango meloen mirabel mispel mizuna mosterdgroen munt nashi_peer
nectarine oregano peer pepermunt perzik peterselie peultjes physalis pinda pruim rode_bes rozemarijn
salie snijbonen snijboon_geel sojaboon sugarsnaps tatsoi tauge tijm tuin_linzen tuinboon tuinerwt
tuinkruid veenbes vijg vlierbes walnoot watermeloen witte_boon zure_kers zwarte_bes
`.trim().split(/\s+/);

function s(months) {
  if (!months || months.length === 0) return '<int>{}';
  return `{${months.join(', ')}}`;
}

function esc(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function entry(id, o) {
  const plant = o.plant || [];
  const pts = o.points.map((p) => `'${esc(p)}'`).join(',\n      ');
  return `  '${id}': VegetableOverviewFacts(
    sowMonths: ${s(o.sow)},
    plantMonths: ${s(plant)},
    harvestMonths: ${s(o.harvest)},
    standplaats: '${esc(o.standplaats)}',
    water: '${esc(o.water)}',
    difficulty: '${esc(o.difficulty)}',
    lifespan: '${esc(o.lifespan)}',
    locatieOutdoor: '${esc(o.outdoor)}',
    locatieContainer: '${esc(o.container)}',
    voeding: '${esc(o.voeding)}',
    height: '${esc(o.height)}',
    width: '${esc(o.width)}',
    growthHabit: '${esc(o.habit)}',
    plantSpacing: '${esc(o.spacing)}',
    rowSpacing: '${esc(o.row)}',
    firstHarvest: '${esc(o.first)}',
    harvestPeriod: '${esc(o.period)}',
    opbrengstLevel: '${esc(o.yield_level)}',
    opbrengstDetail: '${esc(o.yield_detail)}',
    keyPoints: [
      ${pts},
    ],
    summaryShort: '${esc(o.summary)}',
    didYouKnow: '${esc(o.know)}',
  ),`;
}

if (!fs.existsSync(JSON_IN)) {
  console.error('Missing', JSON_IN);
  process.exit(1);
}

const all = JSON.parse(fs.readFileSync(JSON_IN, 'utf8'));
const ids = Object.keys(all).sort();
const entries = [];
const missingNew = REQUIRED_NEW_IDS.filter((id) => !all[id]);

for (const id of ids) {
  const o = all[id];
  if (!o) continue;
  entries.push(entry(id, o));
}

const header = `// GENERATED by tool/run_vegetable_overview_gen.mjs — curated NL vegetable overview facts.
// ignore_for_file: prefer_const_constructors

part of 'vegetable_overview_data.dart';

const Map<String, VegetableOverviewFacts> kVegetableOverviewFacts = {
`;
const footer = `\n};\n`;

fs.writeFileSync(OUT, header + entries.join('\n') + footer, 'utf8');
console.log(`JSON total: ${ids.length} plants`);
console.log(`Wrote ${entries.length} entries -> ${OUT}`);
if (missingNew.length) {
  console.log(`Missing new batch IDs (${missingNew.length}): ${missingNew.join(', ')}`);
  process.exit(1);
} else {
  console.log(`Missing new batch IDs: none (all ${REQUIRED_NEW_IDS.length} present)`);
}
